### ISSUE TITLE
kitten script loading

### ISSUE THREAD

**Issue by Molinko88** [alisww/alis-opencomputers#1]
I want to re-work how scripts are loaded and stored. Storing them in /lib is going to pollute the dir and although new pages will overwrite say `.0.lua` and so on eventually there will be leftover scripts just lingering. Also it would be nice if multiple scripts shared an environment so the browser could expose variables and scripts can share them as well as some states.

```lua
function browser:parse_dom(page, page_name)
  self.dom = xml.newParser()
  self.dom = self.dom:ParseXmlText(page)

  self.scripts = {}
  self.script_env = {}
  local counter = 0 -- maybe this could be a hash string instead? uuid?
  for _, v in ipairs(self.dom:children()) do
    if v:name() == "script" then
      -- if scripts had hashes then we could cache them and only serve updated scripts?..
      local script_path = "/tmp/kitten/page_name." .. counter  .. ".lua"
      local f = io.open(script_path, "w")
      f:write(v:value())
      f:close()
      -- now we wont need to define script:run() in each script. When the dom is loaded
      --   we can just loop over self.scripts i.e self.scripts[n](window)
      local script = load(script_path, "="..script_path, "t", self.script_env)
      table.insert(self.scripts, script) -- save script to execute later.
      counter = counter + 1
    end
  end
end
```

**Comment by kore-signet** [comment]
I do like that! The problem with hashes/uuids is it would require the user to have a data card.

**Comment by kore-signet** [comment]
Maybe require script tags to have a name property?

**Comment by Molinko88** [comment]
I've thought of using a name property to, but I don't like the extra crud.. uuid can just be generated using the uuid lib, no data card required, and a hash could be slow without the data card but do-able. Maybe we can get away with just the server generating the hash for pages and serving them before the page. Client checks if they match and sends a falsey value to retrieve a new page version or truethy to indicate we have a cached version.

**Comment by kore-signet** [comment]
That might work, yeah.

**Comment by kore-signet** [comment]
alisww@6841343912d0ec3e70d4e0c6cf629659dc550f81 < fixed here, though it still uses a counter.
